trigger:
  - master
  - next

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: ^12.0.0
        displayName: 'Install Node.js ^12.0.0'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: i -g npm@latest
        displayName: 'Install latest NPM'
      - script: |
          node -v
          npm -v
        displayName: 'Print versions'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: ci
        displayName: 'Install dependencies'
      - script: npm i webpack@latest
        displayName: 'Install "webpack@latest"'
      - script: npm run test:only
        displayName: 'Run tests only'

  - job: macOS
    pool:
      vmImage: macOS-10.14
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: ^12.0.0
        displayName: 'Install Node.js ^12.0.0'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: i -g npm@latest
        displayName: 'Install latest NPM'
      - script: |
          node -v
          npm -v
        displayName: 'Print versions'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: ci
        displayName: 'Install dependencies'
      - script: npm i webpack@latest
        displayName: 'Install "webpack@latest"'
      - script: npm run test:only
        displayName: 'Run tests only'

  - job: Windows
    pool:
      vmImage: windows-2019
    steps:
      - script: 'git config --global core.autocrlf input'
        displayName: 'Config git core.autocrlf'
      - checkout: self
      - task: NodeTool@0
        inputs:
          versionSpec: ^12.0.0
        displayName: 'Install Node.js ^12.0.0'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: i -g npm@latest
        displayName: 'Install latest NPM'
      - script: |
          node -v
          npm -v
        displayName: 'Print versions'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: ci
        displayName: 'Install dependencies'
      - script: npm i webpack@latest
        displayName: 'Install "webpack@latest"'
      - script: npm run test:only
        displayName: 'Run tests only'
