trigger:
  - master
  - next

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: ^12.0.0
        displayName: 'Install Node.js ^12.0.0'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: i -g npm@latest
        displayName: 'Install latest NPM'
      - script: |
          node -v
          npm -v
        displayName: 'Print versions'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: ci
        displayName: 'Install dependencies'
      - script: npm i webpack@latest
        displayName: 'Install "webpack@latest"'
      - script: npm run test:only
        displayName: 'Run tests only'
