trigger:
  - master
  - next

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    strategy:
      maxParallel: 5
      matrix:
        node-12:
          node_version: ^12.0.0
          webpack_version: latest
        node-10:
          node_version: ^10.13.0
          webpack_version: latest
        node-8:
          node_version: ^8.9.0
          webpack_version: latest
        node-6:
          node_version: ^6.9.0
          webpack_version: latest
        node-8-canary:
          node_version: ^8.9.0
          webpack_version: next
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: 'Install Node.js $(node_version)'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: i -g npm@latest
        displayName: 'Install latest NPM'
      - script: |
          node -v
          npm -v
        displayName: 'Print versions'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: ci
        displayName: 'Install dependencies'
      - script: npm i webpack@$(webpack_version)
        displayName: 'Install "webpack@$(webpack_version)"'
      - script: npm run test:only
        displayName: 'Run tests only'

  - job: macOS
    pool:
      vmImage: macOS-10.14
    strategy:
      maxParallel: 5
      matrix:
        node-12:
          node_version: ^12.0.0
          webpack_version: latest
        node-10:
          node_version: ^10.13.0
          webpack_version: latest
        node-8:
          node_version: ^8.9.0
          webpack_version: latest
        node-6:
          node_version: ^6.9.0
          webpack_version: latest
        node-8-canary:
          node_version: ^8.9.0
          webpack_version: next
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: 'Install Node.js $(node_version)'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: i -g npm@latest
        displayName: 'Install latest NPM'
      - script: |
          node -v
          npm -v
        displayName: 'Print versions'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: ci
        displayName: 'Install dependencies'
      - script: npm i webpack@$(webpack_version)
        displayName: 'Install "webpack@$(webpack_version)"'
      - script: npm run test:only
        displayName: 'Run tests only'

  - job: Windows
    pool:
      vmImage: windows-2019
    strategy:
      maxParallel: 5
      matrix:
        node-12:
          node_version: ^12.0.0
          webpack_version: latest
        node-10:
          node_version: ^10.13.0
          webpack_version: latest
        node-8:
          node_version: ^8.9.0
          webpack_version: latest
        node-6:
          node_version: ^6.9.0
          webpack_version: latest
        node-8-canary:
          node_version: ^8.9.0
          webpack_version: next
    steps:
      - script: 'git config --global core.autocrlf input'
        displayName: 'Config git core.autocrlf'
      - checkout: self
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: 'Install Node.js $(node_version)'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: i -g npm@latest
        displayName: 'Install latest NPM'
      - script: |
          node -v
          npm -v
        displayName: 'Print versions'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: ci
        displayName: 'Install dependencies'
      - script: npm i webpack@$(webpack_version)
        displayName: 'Install "webpack@$(webpack_version)"'
      - script: npm run test:only -- --ci --reporters="default" --reporters="jest-junit" || $(continue_on_error)
        displayName: 'Run tests only'
